apiVersion: v1
kind: Secret
metadata:
    name: authentik-db
    namespace: authentik
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:VnVMg3N2bMIf,iv:FlVRol6bFc8rPGYQp7LG89y5GdXf9X+NHAgyKn1kQp4=,tag:TKV7YMYusEu0zUlYHq4R0g==,type:str]
    password: ENC[AES256_GCM,data:MKxpiV81I2gQNQ7vNfR7oNPItcK5+O6hOaoX59qkPCHKa+FLVfwLoLzO/UaSGlII,iv:WALvVGP0AQq310IL0BIv0/IS0dd2Kt5AXZ3fpIYexww=,tag:HmaHLAK/e5KnOKFxwFbuhQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:nmgN4zaRZekRAv2AYBLOPIdZvWoGAN56uT5RE/tlbAeCXXhnQXmoqFtnSXYxy7dz,iv:vWbQQLw9tgbup9Fy4LlbNizJE1zPy6DNg+RX9j7YySA=,tag:cEW+XkZEFIpQ8Es5WsLJ+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQ1RaZFdVTGM1MFlscm9P
            MGNXY3JXWlJXMUxya2x2cUViVllQNndWNm13Ci9memI4WUZRSmZ5bzY5TjFRM09s
            Zm1RQUM3cUIzKzBFT3g3TWlrWnB2ZW8KLS0tICtROXdOelpFYmhGWkhSeFdwbi9S
            TThiRkF3bTg3WnNqaHFVUGY1cUMrc0kKOIwKYxfyxRW51CCWL2Xe2XsonPmwzpU2
            L7LtBuYVz7HwjybpsJ9RkQ88QQw+zbL8B1gp7mWGt0KNPTZRaW0TTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15ry0az96h329q6hwvzewyl0re9gl554n73megqyk276kkrr7pvuqpyp4y8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T23:52:58Z"
    mac: ENC[AES256_GCM,data:vLAQp+JtvZszNDx4FFSinjGRj0VWhbl9Ds6S/Bdha/boVAiOpGtabgTf8Bi+9+zbHde+f3LC2r21un09qWxaK2poje4JJTL3FFLiY5K7TtYI3ih4ETqy2pWzKXI+H6rOr8A09SbdkumcoA9/cYMsTm+heV95A3EIzOysRYdESEc=,iv:WUVsoBH6tAKN5u7oDw1DOGdCLJqqKq/L+zU3ir6F6OY=,tag:gvbN+e/FFASYGTKuRmYzlg==,type:str]
    version: 3.13.1
