apiVersion: v1
kind: Secret
metadata:
    name: authentik-credentials
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:Sx20CeWko+ZLJ+6F5Afw0agY75MmBwLcutU1XoyV2awGOgYc3C9UtKmftyhbjsOZ1NjBNN0+W6oVSaz2NnFU8g==,iv:r26+NBB9aU/n8SWUYrvzoG2IzcaUiSBAfPSuwLNIAOU=,tag:MfVhfp8f3/ybIYN6pmazlQ==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:00e6PjXcAIKoe7oN/PU4fmt9w6rb,iv:oCbaDaL4vznriTdAh4rRFRwpScHuLemjE/ScJfqEJDE=,tag:VZuRtUmEOLnXhTUenRhnqQ==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:zSguQnrcVXTC,iv:KqbPlEh7Pvj7m1F443KlG7KyvdVb95490yyjCoolDLQ=,tag:1IDVcMPI7onYLYrBMG63qg==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:sqXd3tAV1ulk,iv:4HwL6w+13zEdQKRg5Usm/rsGPXqKT0AQcENrdiOy/60=,tag:EH1sLfGw/yBAUpQRFK0Gdw==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:JUEXMNcOvIsC9RwoRkWiFiAVnqCBlX5tvGu/759wDGtS2LX93Mu8dXqojaPzyxgn,iv:4rvydgjpmETGprPO9hML0fl07Hj6Q5B62XM/4GwrNBA=,tag:NjykurfqfjlaNEfjhwIuzg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNXkxWDBsVEtYRTFiaGJE
            UzVNS1JMNk43enVyUHFKYmJsR3ZIcGFmdlZVCkthWG1BV3RONkc3d3NVTlg3cGZT
            Y0c1ejhzTjNLbkJLdWh1UlFPY1VrTEEKLS0tIEwvbmx3Z2xsZ3lqWnVBVGs4d2RD
            enNLRkdtemxkRlVpazJtdDRjUFU4T1kK0e4tQfK0myB7/+OtkJL+g+SHX8aFArEg
            fihzgp1C17WHXrG0WIpXl4HrP2ToNdMQBo2jgAwd9JF7CDxQM/DvBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15ry0az96h329q6hwvzewyl0re9gl554n73megqyk276kkrr7pvuqpyp4y8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T23:52:58Z"
    mac: ENC[AES256_GCM,data:92MXBcI6g4YJdEJAVk0d5V8E2PM0VOA3aekOigQ94V9hraqiMbuYj2nwXehvadsTaXFZX4i3EX3Gy3M9TO4DQ1LDVVbr7C66jPzaGJ5EnGwqGHhFR5B/F0+9/uTIng6wMKjqU3c1OpE6lfvDJMY9qildAXlbNI2QX/nNM80Uc1s=,iv:ZwsR8ZFRH2DmkRmPEqY3dXxISs4pstHxInwVXpxvx1Q=,tag:duMH5LhuxCDkR+r0Vl6nMg==,type:str]
    version: 3.13.1
