apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgres
  namespace: authentik
spec:
  instances: 1
  storage:
    size: 5Gi
    storageClass: longhorn-nvme-202
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-db
