# apps/base/paperless-ngx/secret.yaml  — encrypt with: sops -e -i secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx-secret
    namespace: paperless-ngx
stringData:
    PAPERLESS_ADMIN_USER: admin
    PAPERLESS_ADMIN_PASSWORD: Helen$2017
    PAPERLESS_SECRET_KEY: YimywRPde3+IQuoZwiAFqHCZr3Q0NxvCI8mVnR4VwXlY3iFX5Zc14JvgL2Nj/kaU
