apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx-secret
    namespace: paperless-ngx
type: Opaque
stringData:
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:wTJhICE=,iv:vFGZa5hK/tM5FjLHk8pNfrHDufAYpErVOTOUAuB3MYA=,tag:yeq0wgquC1dtPamo42xJGQ==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:P18zKhwSxV7jx1gOM91woDGnW4RFi8QQoH0QQKQ=,iv:FGwy+2SUBfcBhFPaerQIutrMUom3NHTci6FxA9iUE9w=,tag:BIzHv60BXQx09ysVxhxnkQ==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:Cz9cDBwLfdqcS1NOS48NO8ipUKdJJdPynYGclvdo6yDA3/ksVZ00i8X9yZKgtctCxnEnOiOdTpWJJ0SMh8a1yQ==,iv:Epn7e4mD890jlOJv6VgDSysH4Z1WbUsupOr3HRQ0fV0=,tag:smatRdN6MgegLVOOLY8yBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WTNLUjBhaWVSb3ZnbU1n
            N0V4ank3N0tpcEwxUU0vVkoyZFA1WjkvdzJNCkFDZXpkcVp5R1JxZVlxcHZmVTdr
            dmk0Mk9CRGVERUJMSWVBa3k0NlhkYmcKLS0tIDRYak1wb0x1OExXdGVxUEcrbkRQ
            V2x5K3ZuUDQ3T1FQelRUOG5QaG1IWWsKvu6QlYTKF4kXdWnVvXMNQKSW2mtKj+t3
            ro0teLg6+5MNGdkc9njfIWD5TWaHcWVKA+a+S1gwn6A+DOYN64s3WA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15ry0az96h329q6hwvzewyl0re9gl554n73megqyk276kkrr7pvuqpyp4y8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T09:59:50Z"
    mac: ENC[AES256_GCM,data:nxvzBhDx64bP10vwF/yeMJ6TkbXiZ+mqZQEb0AapftebEJNu2+fWg8Z0pbVdtPpxnlc5LtWAUXbRa+4V6S0jk5t1MFwNv09/dtBIWGZ2RjNcfHmNYKuhq4+YG9TRdUFJJ+q/JHuxDLfQx95hwkTjZy7knCdbE8f71K7NqvMmP9Y=,iv:GYlVFhSwepEI7+Fyd78JfOIPDwzAQsZ/ZqONKcrn4mI=,tag:MYlOaFzTKqIxc3tS4OHqZw==,type:str]
    version: 3.13.3
