apiVersion: v1
kind: Secret
metadata:
    name: paperless-oidc
    namespace: paperless-ngx
type: Opaque
stringData:
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:+cBqoqw5341nwUrF9gN88C/SOfdG0TYw34/qxzeZCQaXhQGAW/z7lIZVaUcgS4HABGO23sFOVTJra9K/UphyDgMynoPKWVifeC6dobHoaKP73ESw89AnBBG5vYmSvqh7G0KtiNB/z9TOyed4n8bxoOSPVlb3P0/V+7QlY5Pg9/+PSSjLoZyS54TATtY6tvmMpw/lMdxTlEWCEMd2D1uVZupvUhs6HbvLTXuADdz4pjJiabLt2zvaVlTYW++QEt7EPBG7TiheKVYULbXW4pwpbc4HCK3X8tC0NZKK5A5yJz9NFjOMuKGku2tXYX8j16VRpPYBwWwwOnY+yj3VdF7SqkLX9s5Vby5OYLp4la2ZaFbKFpYSHJZT/f7mF8i/pIh0QFxWXHAaw7hXYFCvqYoE2q6CBpQTS0g=,iv:4xNiAm/vmdp2NnYP9yzBo4lBJmvNhEoiu7GcNobVK4Y=,tag:vifsSsQCYTDFoOdtFkMi0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaGlQY25tb0hhZXJpK21M
            WWM4SmR6amNGaEtURC9VcSs4aU5lVzd6ZFEwCjdCWURWY3BBZ2tDakF2bDFDWHhK
            OXBzYXUvNkNHSVBScW1nYzkrWkhXc2sKLS0tIDhPVWJoRG1Id01sTWpQK1N6WEFr
            STlLTkNVSFdlMlBPOXUwRjBtUWEyUHMKx31Pjvyg9xX5pu9OKx6YujYtLqmKUz2U
            4EYMVQViIFdfTiNESMx8myFi1Z5r0KkloAsiU2d2G0v6mV3Smj2ezw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15ry0az96h329q6hwvzewyl0re9gl554n73megqyk276kkrr7pvuqpyp4y8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T14:19:13Z"
    mac: ENC[AES256_GCM,data:/kRXWClLeHhShmdEJXHmu5bDTk173mQGCN27qKsEJFdFaMbxtav7/ZoOwKgQDKse02yyKTiisU9KDVNlB9jTSH3S8Jg6L8XVMZt0+d0hn4hEylHq8X0evAAnNqLw48M8bsViVz2vfGnPJswHgGGT6rQ5r4dDIs1jXoG1JXO0p7k=,iv:2qp63iceiVx3RYSBpBRoXKmKbJGjV5T3H88VT9lj5B0=,tag:47flKAMtbFZagqNewqQ+eA==,type:str]
    version: 3.13.3
