#ENC[AES256_GCM,data:RBum4EkJXAmBIZNSwRvgSkd1ul0v0q5+hkrP0G3fTEezjRGKPmH+LT23b4VcR0jRt8kt6FRTR6d98m8D8/+4LqzadrBHpsHuOHarggiK,iv:5MOkJWDdYkjyL05SRowil2bRA0Ai6ZMuJ4rAyB2BJSc=,tag:wdY/ocZs/SNZvwR7JfNirw==,type:comment]
apiVersion: ENC[AES256_GCM,data:8UE=,iv:MneT4DKEpAV6Xvro0ERvISkqgBpSF9cn1sh8j16e8gg=,tag:xtCnlbpmCWvnm1Hv9o3ZjQ==,type:str]
kind: ENC[AES256_GCM,data:UcARo9km,iv:EwkVeEYh8lyIyFHhclg6yZvMAGlTs+LkmHdu3uG1yUg=,tag:6ixyxAW/LgFA/OfZ/S3O4Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ANYc2fJjqanpvEs0hDd+JFE+yqI=,iv:hC6rOxnYsrSAZc9sdBgQ+gsSrZa6KY29XGWJLDRMdzo=,tag:+5ptG1t7wmyo41T9MyqBTg==,type:str]
    namespace: ENC[AES256_GCM,data:xTWk2rPgaIsQ7lQI9A==,iv:dKjw8rKcp2qALlrEynIgrJxcRHJVVmAWePor/iB9H+E=,tag:GcOzBQ9OQ/o6kTubNcU5KQ==,type:str]
stringData:
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:Vvznuuo=,iv:5rXu5kfTPe7FovYreFs2OlgbebUDniewGXaTGt1Rvbg=,tag:RKVAg6esV3UAdAgg3oFE6w==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:KCscVlETO1k=,iv:XhgH+OQrhg38Kye18GZGI+egGhFHUPSL564vZkxlnEo=,tag:UFKErbNExI4A3IiMr6Iz+g==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:j7whaUBg+7zSKDUJKjwdOOc+vW8=,iv:Uexkz5x+jwiFRcjw2Oyzyo6q+t77svKsmaEe9lmJ9vo=,tag:2vTh23hwjC6VN8DDGn6QAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TlNkMHU3MmxWYU96UHdx
            VHlDcTgvd3BqQit3Sk9Pamdxc1RCeU5xVUhVCnFhQWtZaUZNdVFjYTFsc01DeHFh
            MlZxaWU1TUJ0Z3M1MzlGdGN3UCswQm8KLS0tIFExSW5lcUhrWGNQM0w1OWljUXVt
            TDZGQU1Sd0MzQVMyZ25KYTJjd2Q0YWcKU591uoWsss357nYb+XGEH8m85S1igJNt
            GcDPPlodO/zTwsoUR4M2iMjJp72uag9naJwY9LYXZV06pC7LW3cypA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15ry0az96h329q6hwvzewyl0re9gl554n73megqyk276kkrr7pvuqpyp4y8
    lastmodified: "2026-05-29T00:01:14Z"
    mac: ENC[AES256_GCM,data:O2xus/rUBVgMiNs/OCnbpD4jfqZlNCobddHvXv+FGLehFdtmlZmdEnaChGGqhYq0W8hXhS+6bUUb2NVGWe8q3Py6Cj9xlllhdaVSAPeTbDJu1aSaYErn7cA6QZuiQo2Tc1F6d3LrMyCvUyE2x8cf1tiFqKu4m+4E6LU9XEb+Dbo=,iv:QDE4iLbuswBbW+ECVA8+YeWaGw/AWwB5xiIJmCKgyNc=,tag:aX0xgbeg+eQVKGvOBjWn/A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
