apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  values:
    server:
      route:
        main:
          enabled: true
          hostnames:
            - auth.passer.lan
          parentRefs:
            - name: envoy
              namespace: envoy-gateway-system
              sectionName: http
            - name: envoy
              namespace: envoy-gateway-system
              sectionName: https
