apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  values:
    persistence:
      library:
        size: 900Gi
    postgresql:
      primary:
        persistence:
          size: 50Gi
    redis:
      master:
        persistence:
          size: 5Gi
