apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  chart:
    spec:
      version: ">=0.1.0"
  values:
    storage:
      data:
        size: 2Gi
