apiVersion: ENC[AES256_GCM,data:kFA=,iv:mx9RilVSiBtipCoXy0riBFdcVebdzqxxLoYY0ylQnIs=,tag:xwIFTV+Qdpe0YR1uXwFXKw==,type:str]
kind: ENC[AES256_GCM,data:vIV3pU/w,iv:DI0lqDfoxUvH+WyZT1AO4wO6gKu/B5vGqcvey+6dc58=,tag:iunSOpcISjfiFgZCVo51ng==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SYLntxfV9+d1cha+,iv:+KDCeAo3MUoii64/urw40LBf3N8Pmb0SgOl3qdLi+KA=,tag:Jv3NqV4Jur93p0MF4f58Lw==,type:str]
    namespace: ENC[AES256_GCM,data:bsCQNTqZTPK2,iv:OtVk3i/LTNl8rOaNzm7xpZXt7R1FOD3GqBB8AFSJQw8=,tag:s7+p7QRsTzksUZBjWiELnA==,type:str]
type: ENC[AES256_GCM,data:mgfDMObd,iv:rK1qh4JWwUgNXPfqV069PtdUq2uFO0mxCrOqGGzBUh8=,tag:mOVzfU1QrACGOF5VJk9akQ==,type:str]
stringData:
    db-username: ENC[AES256_GCM,data:liQu9VSJ3jQF,iv:eFA/gw07Q0knmnLO5ee77iEw91e8c41q4H3t03lXcjc=,tag:ffiIyz3keVs/C69eGqUHDA==,type:str]
    db-password: ENC[AES256_GCM,data:r/CFaWDkMbo=,iv:Vy/sURH3dqLh0keGhVxD05ucF8LzDyhWZRFQQE4QbZM=,tag:gkpbZHlRSb7xJUWtB2EfTQ==,type:str]
    mariadb-password: ENC[AES256_GCM,data:TW9AQjGhBNQ=,iv:qcr9tz1YkHeDdIYdBkd1hNUVNpujTY/H/38/rnaU2/I=,tag:Zgec0uTzPG367u00kHWFUA==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:Qz/FP94iZvU=,iv:g1dbevU07OqL809ESAqCTrWm7emaFbw+vF4x+7I9Vyw=,tag:rK2TYJh3RnmlO9nmbtLkHg==,type:str]
sops:
    age:
        - recipient: age15ry0az96h329q6hwvzewyl0re9gl554n73megqyk276kkrr7pvuqpyp4y8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGN2NEenQvUUh5ci9NM0hr
            amd2VkoyMVFLcm9pZWZMcUovUHBPZmR4MEUwCkcvZjZsUWd4UW10Vzl0Y3c3K2hG
            REZMNHhxcHB0VCt3clFIUUVrOFQveXcKLS0tICsyci9EQWsrTFFWN29Jd08xT1Ju
            WUI0bWRZZ3R3NFJZM1hnR1hJVjBZSjgKpMb5yQqaa0W9lH42PfJxEcAfIQrGoxJy
            KF6Iq5l4+yjtYXMMX0mzKWmO56gNATmDBQuuMicyPjBC7yp2ppsgFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T23:16:36Z"
    mac: ENC[AES256_GCM,data:Lrh4WJPC9V7yjWJCz3kYJwTzWCJ0hlB/a8MWI2DZTXDbyB46o5wnFAF00AmbQTI5WGDqSoFrTywOpXwWPyabrzDDsnXJnkf3Y2TbAIXb7QBBJPfAJDKpWlIS0qBFsXrlrIZdVsFlU0mAs+KfPH1znfXFyCsf07Khp35G7sSoqjo=,iv:iyJxC4/5XckWCCnoi/GNQXy7HnN2RF2/lRyNBox1ySM=,tag:8j8uFtRSmEsCgFwhUImokQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
