apiVersion: ENC[AES256_GCM,data:WXg=,iv:6n0lLvCi4zJJJ2YzRSuWhOB+Qwfpv7TJK3z7jF1Tf58=,tag:ku0Z53Kq+BVVeaAwiUc5tg==,type:str]
kind: ENC[AES256_GCM,data:y7ygK+KU,iv:BVH3L7BganDkkEP+7dUJnwCyMMROQtRoxbs3jSKbCs4=,tag:5Urljthmvp1A3ID6P8BVbQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rCNq8pm86unRSU7qvjI/NEs2bwx+,iv:xSOS808G89ZHZmYosCzeipkjcmaHE+VsfI6LbeuD9hc=,tag:Bh4XaIhy+w1EfPsvw7UDVg==,type:str]
    namespace: ENC[AES256_GCM,data:iuWaicny+EPi,iv:ctCKtReViqnog5m0JSzQVuFdUXSRO0zue+eaQC7iCX8=,tag:DVETPA4/rlTIgb5+Rsowyw==,type:str]
type: ENC[AES256_GCM,data:pyuM1UIU,iv:cLQmRYD3ZHfugM2b2lO6vg/TPPtJqAtVfcmDWSPK7Kk=,tag:0duLSxoTZpKDFpLeGtYu9w==,type:str]
stringData:
    nextcloud-username: ENC[AES256_GCM,data:R0hYdM8=,iv:1rBzpivDYRxzspPOzU3/7ErLv5FjCVMjGUofJrCvGSk=,tag:umadh3kbhNq9OWZebQJ+kg==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:fmceHvBmrWw=,iv:xui76Rp7h/q++gQbu1JVLVRmEPEL0/Rc4wTu1OhjLT0=,tag:F0EIqLGEZn6W8CgW44/utg==,type:str]
sops:
    age:
        - recipient: age15ry0az96h329q6hwvzewyl0re9gl554n73megqyk276kkrr7pvuqpyp4y8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWmRXNTkzSzQrT2tIbFo1
            RzhEaHMzZzh0YTNEenIzVEVpL3I5ZncrbEdBCnQ4d1EwTXcwMVpMMGRyM0dIdmJy
            QlFYZDdRSUFDOTgzVXpjaDRKQXJkeDAKLS0tIFIwODhHWHNtY1pNT3JxQW5VZmpu
            U0dpQ0dpZ3NuRUFFRDY5MythaXlDSm8KS5emy+Yay58ijpBYxz3fusK06lwZundL
            7bXNrxH983RIHXmNUr6hokWoydk5wJZ5FdtBFu62BWh6fSVvGaL8/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T23:16:36Z"
    mac: ENC[AES256_GCM,data:T7MLUZ6LNYEsfxvYfiyhjBomYyiYB9tfB38VPpR+yKX4INJ4KQxhYxldcpzvk9dZLt3uvLoCx9ihYFixVgVZxzpIvG/am8udnbKh/2Y+UXmIhrz5oqVRr6m1P2VwOME9bpOiv8rgnRA4myEYkEjOH6vxbJEQNjAbCF2IMhVeXfM=,iv:MBSRtURisO9SZ0ZrfnlRyjQeiYcOP+KkLfO6AfAIGx8=,tag:HVf3Pyit9RS28AuInS2MNA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
