apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-credentials
    namespace: nextcloud
type: Opaque
stringData:
    nextcloud-username: ENC[AES256_GCM,data:Fy6andM=,iv:P9ObxYeyW9NST4qHoPS8LkXlR4tZJg6POzi1aywkGvc=,tag:1hDQDnuvTIhIcagFWsN2hQ==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:WpGBv716YU0=,iv:cn8Me0zISl2glJ+Ovzcfl+oABiuxHNRor/4ZrFeW8vg=,tag:1JbRUXBny7ANUGGMFUrMoA==,type:str]
sops:
    age:
        - recipient: age15ry0az96h329q6hwvzewyl0re9gl554n73megqyk276kkrr7pvuqpyp4y8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIL1ZKVHUraDk1T3AvMzhI
            c2lkcXV6MUtIdEFXTEVTK2pzSE5MQXFvWmtvCks1Y3N4RExXUUxoQjIrQm50d3ZD
            Y0E5VEM2ZlRHdjQwdnlCZjhManJFSzAKLS0tIGFjWlUwRExIYVNldkI2T28vTUM3
            NGJhS01VaEtPa1dxYWFQSWVkRWlqU2MK0En1zljZnhFpYdeMX7clIy525giKDA4n
            FgO+i1xxf7XVkqcbNDFvPoE9r1cUlydwOsDQdXFd0L/SNzsBNdXQdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T08:25:05Z"
    mac: ENC[AES256_GCM,data:OaAyEaj+S880YG+aGfUI/SomHZIwvKb8gOvLX8dYHQroHfmwWFo5w81G8GVrWHEIQAZzKsO0+FARqP4svri+wl5j1esoZ5IKpT39kkK7GnO9N+7iRKLZyj54YpWU2/vrP1d7R2/U35xX8DUlXv5eIZBKasAtUV4HMXhojoTkl4Y=,iv:EQ4Ua8otf+YnFdT06BYOcmHLj1PkVmaQKXsCnOD7eSg=,tag:bEx0jBEWuoVpvjCQ632f/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
