apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-oidc
    namespace: nextcloud
type: Opaque
stringData:
    OIDC_DISCOVERY_URL: ENC[AES256_GCM,data:me5yytbFs/I7m28e+Q6IEGaaeuJdtXAfRdMPrHvjj9EgFLnjoaAXc1VaUQ8DD35U9xyoxzfnbHvKW7GgTAPnk2+dSBVO5qDDFA3N+rnTY4g=,iv:pqXYKbgbnTxgJqnQFT+fCKKdcsoMzeDdDFqczQa3yXA=,tag:CrYewKke2Rnl8FCvsBWFDg==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:SlbBlGuKNjn3,iv:Oku23+Zjezbzta9vpcMnG+YrpnkVqGqTkSYIe4vQmzU=,tag:/oJBkSYOfdahd8CFOKdzOw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:SnwCMI/+9viiNrj+WZVhub3RssNX0tuUGnL7suHkwfs7UkbuqutbIrDNPs+HeuW0Sg0OTE5inFdc8YTTjfH9zw==,iv:VLISXgMrcMI8G4gHX58XJXbex89WULUJqYM5d9vTitc=,tag:w5nC48fteSh90jkC2rEarA==,type:str]
    OIDC_SCOPE: ENC[AES256_GCM,data:rMO61XEr+d48szymT2qxcg3dtgc=,iv:qZGe2+UuqzInAX8xIhOEyVf4OZHAGjgew461hhAtHCI=,tag:YwohYE9bnri9glxV0jm10Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Qk1qb2tTZHlIQXRTcmVJ
            d2ZUWjRWMDVJMDBvTmNRS1B4Mm5PbnQvMDI0CkM1b3FubW9pZXcvMGRHWk5xV1do
            YkFGUlh1VW1VV1l6bUNPN0RaTXFLM0EKLS0tIDN5ZEo4OHR2OGtkVUNYMDhXOThM
            cUZSM2wyWHNzZnEwenh0SWtpSGZIek0KkMO9bkn2TkTzSFqjPsIvZLhmwmr6Wv9V
            zxWc939SlPa/GB22KDmT43/oroLS2VwXS0adgG1HlRkQbMIhTbEnfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15ry0az96h329q6hwvzewyl0re9gl554n73megqyk276kkrr7pvuqpyp4y8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T14:22:17Z"
    mac: ENC[AES256_GCM,data:mfxnyd4JAlSILvgqtrMJ7ayurgwhvr5aXAY3JQ5cM0SAKzPDjzvLp9lLVmoDM+V5M8B3sAa0QM3XzfknHbqd1CZZQBCKtTVcnLteTg4B6MnuPFEx1qGeE79G8Fmp15pIqtNHuKcbNuivLpSCUlvBJlJZEButbnV5N6cXTE0o1vA=,iv:uYX/nFK5anEef6k35NQ6KkLjgTFIWnXRl8xkDS3E5Iw=,tag:HepINSFvoFb/ohtTIjMPPQ==,type:str]
    version: 3.13.3
