apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db
    namespace: nextcloud
type: Opaque
stringData:
    db-username: ENC[AES256_GCM,data:foBrmyOjnj6/,iv:eWNB+l7KmrqhqttJ3AHwHvSVyGrLN3cDFDdnT3vdnY0=,tag:gcr/XpcIboQDyDpQhB0ohA==,type:str]
    db-password: ENC[AES256_GCM,data:/r2FDOezFZI=,iv:nRzCkrIf/baeDVy4x7H0adgic4cbMRUWFDV2ioGyOAc=,tag:R/4uN+YafMnmXLoZ2sn1CA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:vzwk7GNn2Jo=,iv:OtfbeOcSzUrKrdU39I7IeN7voToAj+r7j/fvCrM9Zk0=,tag:IOtBgjNQxn7k+vP4Qnzzcg==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:7WwDWJC1Wpo=,iv:0/jHVjQnv1um81q5+H7MaD15M3y+8/v8n+R1uc3xqVQ=,tag:T1BhtVzCKWQ7ZL2ybpZ2YQ==,type:str]
sops:
    age:
        - recipient: age15ry0az96h329q6hwvzewyl0re9gl554n73megqyk276kkrr7pvuqpyp4y8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUFJiblpqcHFnUW1jeHNC
            YXVUYi9wRGhzVWsyTGw5R3BzUEtFSkU4UldnCmtVR2Yrc3hoTTc1blpKbC9WYU5z
            QVoyREZMQXo5N00wNEdYRkFvbFFmNGMKLS0tIFB1TGx0bklFa1BaUFpsOFgwY1gr
            R0QzRlNmd0pZR25Dc0VHckQwcHhSdUUKdSE3oFrLSxhQL/lewjPFm6Eb6sIkIocN
            PQ0DrTpKLXDv+ppN58MAIhNDgPRzAREouQ/yL/CKSr3uLOohq5BhHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T08:25:05Z"
    mac: ENC[AES256_GCM,data:qC4+YhVHOS8ruDe8RoHHgDMTUKVLe/soEL5uNIFHF9Wk3OLQITE+OQznNpUX9fGdAgcHX1pWv3w4KSv28eFzLYFiApb2HZbeykEbd1yw6SKaQ4i5/xjyhekos7Y9i6aNAzvfTRYM9I977mSnnlxqijZxdOHwnCiX2VV1k5wyPFU=,iv:hLIj6BUgxHda0P3v/iFL601Nvj2NUTQTWaWZRcyaaS0=,tag:RZfWp/nYaSunXXk/cTQ/4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
