apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway.yaml
  - metallb-config.yaml
  - longhorn-httproute.yaml
  - storageclasses.yaml
  - minio-credentials.secret.yaml
  - velero-credentials.secret.yaml
  - velero-schedules.yaml
