apiVersion: ENC[AES256_GCM,data:bXI=,iv:APGfoqTljIUr9cQwE6KPNnw1aoKZwhpaaJn7ZkcgqlE=,tag:ZdcFJzMBV7KxXf6dsGZj0g==,type:str]
kind: ENC[AES256_GCM,data:n9kMyIj1,iv:EJkpL82GXHZjaXQFKDNAo6DEmuyF50xzSVGhXhN1LDo=,tag:AbbOhqjrON6hJu4efDT0HQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Nrld+EqC5/DiJY0ZMn2XDhc=,iv:MxxBT23TMtgcD8xtQ5/oKt5cQWWdZ78NxitGsf/r6Ms=,tag:Ot1MGTnNd5YVP+iuj/uMxQ==,type:str]
    namespace: ENC[AES256_GCM,data:cq/F/5s6,iv:df2NKTIrw19kd7iLKsprWLLzBRii0TCJv0pcRwqVWuU=,tag:kx8Ol+oz644mFItM83Nm0g==,type:str]
type: ENC[AES256_GCM,data:crrgfBP0,iv:nywgxLfPmglL3wmJ1beoWLs/qFmyfMb6J3MHc7u4TCE=,tag:z0mqMCseMkPxl33P1vE/EQ==,type:str]
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:k+1n8O8=,iv:aLW+PKRteyHgcezmNUeu4bESff9e3nE5/x3NM6Nnsgk=,tag:WaywaDXX/+nGwi0y1ZRA5g==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:GM+AuJ7RKDTJmw==,iv:ViDXrwOx1XjQ0Thy1YcRJaBCmVhZbgcwUbvQ/mB/aZk=,tag:ELkwPgWt94w7qAPMnkYHNg==,type:str]
sops:
    age:
        - recipient: age15ry0az96h329q6hwvzewyl0re9gl554n73megqyk276kkrr7pvuqpyp4y8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UlpRcFU2ZmZjQStpM0Zu
            aExnVWs2azEwVnRvdms5dkRYSlhJWXVUakhNClVDVUpETmV4YU9Ta3VjNW5wREdo
            alhCRGVCQ3plRURRcHhaaEg4RkU1Q0UKLS0tIHFNS2RJN1VUM29EOFNNaGxaUGh3
            bzVoaitwenRVTGpNK2gyT0RjWWcyanMKGwmoj6USsqw6RuP0VEsDQinG9TChF2Pl
            T1yQLFoPTkP2ggKxl8IUsYnzq6biTDI/nr1BSLRAe6it1H7ikzhuzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T08:19:26Z"
    mac: ENC[AES256_GCM,data:te4TyRZwBtoTWojN5gyFM9dM2ntlIdc+WfUrQCfYdI7vGbRhookHUF8U+W4mCeKl0ltIsy2rsM8QQ2JIetHWs3oU3Fv3cURZuGZ3wfdul5qXrQW6nYDUvQ8YkdpppreyJlDD1+1NXD2KaSW4T3JEf2XwHeLV7z3ZfPLXT69KUY0=,iv:FtA4PXVcSNw+e/1hbV6z+6C6LG8EnOjBmAnuwBXn6Z4=,tag:P4696r1s57aEYvVNIANnhg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
