apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: velero
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:LlOugpY=,iv:VP+R9pi7cuZWJDdi0TCoACz0aI4ilZZ+JMdI0CYAjEM=,tag:KwxOMpCTTdwVFDFk0g3dlA==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:duDeKgqbHG7kaA==,iv:espipoEZaiNl6IJahfXmrVhPSHGIAzFEPxGw1cwhPPw=,tag:bigQgu8tOudiGGmNclcGKw==,type:str]
sops:
    age:
        - recipient: age15ry0az96h329q6hwvzewyl0re9gl554n73megqyk276kkrr7pvuqpyp4y8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTmtFRUhTb2RxdlN2OGww
            RVhjNm05ZlBVU2dvdVA4VHQ1UUt2aTZ6WENjCk5zMVlnYjZOYzV6T1NieDZvcHVz
            M1NYTHdHYytORlRpZ29JajlWTk5vdXcKLS0tIGt5VDdvaE9pZXRxZ0RXLzhKczdR
            ZEFKNVNlcFlQRWMrZjdhSThOUmtuU1UKh17VK+5BxNUK9IIlS3qQQZ73kdvNYeIo
            Xngt5cgnVOXETHfeGMIedIwQIv+jmvqATrN1d5ZVrjDovLbTkpFjkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T08:25:05Z"
    mac: ENC[AES256_GCM,data:s2P1UW6QwIk1v8wumkwy3CqB1rHkwxGsAbvJdF71q0HbrJWP52CM08aZXyD3n41ysCaTcs4sYDTR+F9aqvd7I7xw9Re56EI9+V480pN0fchQl12sXa/Og6DTJEjv/Vui4tpR8ZlLhJz9FgqS9v9p4VybJSbxbfXjKOW7KhRQq10=,iv:Zu5UL7y03XrzE0ojN7rkES1Kg3px9Zbma5hTRrhfozQ=,tag:jwNog8gvFolwyhNU4XLTnw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
