apiVersion: v1
kind: Secret
metadata:
    name: velero-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:K8z0f7V+VfgpDEnYeZCCvMFWsoclPeQndU4szy85vTvIRzK7dMtpceq8j84WAO/mpjGkXVp5V1U8ppFzbgVbp5Lu81j+Pf0=,iv:B4oAy6DEJYbSWPEtOqbOWTJKmO9fCYquIbHYkOrrS+c=,tag:p7RZ5C8iWm/H9aSCtKIlLA==,type:str]
sops:
    age:
        - recipient: age15ry0az96h329q6hwvzewyl0re9gl554n73megqyk276kkrr7pvuqpyp4y8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MjBMcVZCTW5MVFNISms4
            dVVTV2s0aUl5NE13NHEwQkpOYkxkOTZUb0RNCjhaMTBCQ1drM29kWkpPQnZLZnh1
            NEN2d2d5OGpRd2E4WHJ5bmlaekUwMUEKLS0tIDc0azF5SnhlelZaTU0wTTR6S0ZQ
            ajRIcituYUxVOHBTZ1IxOFRCcXh3MEUKIXR25C9f7a6rN09lElPOset6IEBA/PPb
            +wmwI8uAzaGzWF4lgWbk8qxJ7TzRuW1hRrdNX2kpVp+c5LElLyFPbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T08:25:05Z"
    mac: ENC[AES256_GCM,data:iXAT/XKQpH6UCeAbZvyC6mgIrCTOwRIQmd98EJ5SKZponmnaEP3tQW7qyc+6eNzcDpnmEfH7/i73MaFVvsjc7zH8cEHn8GGgAZX6POLBiqr9aLtirzIPeiEEluma2YhTcGs7nKTwmowVIixVHq0ybm5xKPa8qzdmW2mKG9Umyqg=,iv:r7Ko168+dSP2wV5+7qWSNCBYg8RbMrjdwcbEB6P1iHU=,tag:zhpGGJN30nD5CttJ4CIrxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
