apiVersion: ENC[AES256_GCM,data:3+w=,iv:izmJyP3LzxkYbp3q/q6ZPckr0daR3rJxZxsWrp4jar8=,tag:mq05P6PABeRD6CTewCZFDQ==,type:str]
kind: ENC[AES256_GCM,data:qD8qFapE,iv:MlGTce826mrmhPOKYbAI9f+GjkRWQbe1m0LJbMu08rM=,tag:eOThJWnnH/vPdUPKfuEbRQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hy4UV7om0ac6vuhQ1Vl4uCbU,iv:2tVIXaf8QPux2XU0UcZGLYYnWwYVK1e6eXU7l0n0HAk=,tag:emONsKVjlYd9V6GltUZuvQ==,type:str]
    namespace: ENC[AES256_GCM,data:hV0xZua3,iv:pRzdfl5ph/Q2ojkH6s9UoW5PybB0uweEiF7Z1LxILck=,tag:dLP1x+zPmC1wHoP4vQtsAw==,type:str]
type: ENC[AES256_GCM,data:6ZpTbEAN,iv:4nh5nQePUfTaoiYSy0owgSKLaOrFP7pOtT3iT/1vCuU=,tag:lVzruscwDTimKIVM7oy3/Q==,type:str]
stringData:
    cloud: ENC[AES256_GCM,data:1Cqj1D3ACODrl6iqVSBkPSuE4qEarwB70xbsMUEz6sVf4uKDiWtrjLBBfPqShUsDU8ITl03V6S2qJr16uxpTi11FlxE4cbE=,iv:qveGb/qn1wLIKETzFNZS53AjAsm1ApaEjV96WcKHHQ8=,tag:sBaA2D/7xLSDV8251HHv6g==,type:str]
sops:
    age:
        - recipient: age15ry0az96h329q6hwvzewyl0re9gl554n73megqyk276kkrr7pvuqpyp4y8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSi9kaEQ0MmlZNUVEWWQ4
            Tm5qNGNtck1GMUdnZTBrcnYzdWFMb3p5UmpjClJUbnk1aUNjaGd1cmJKMFdYK2R4
            NXVSSnJkSlduVGJrUHBuVnMvUzYrcEUKLS0tIHhFRUVka0NBWWFsOFNKWmJBVTNU
            NHFURHlqSVRaVldrYTRWcUdJY2ZjZHcKWkj9oKNqWZ/tl9K9QkxqgVZyiFBaNCG+
            Z2a+QGjtGB1NTkemSzn9q6pMOelHNT7m3dWR6scN3UZT/Uk6DdhLww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T08:19:26Z"
    mac: ENC[AES256_GCM,data:WweLAlq9beCWL02EpIUemeCwiXU5Z+z68ek7kLjxaV3FgRqqSWgn0jn0h7/htdI6pajX+H8bm1BKZhH1mXBsbvEr2cfdmliCeoytpnm9Gn8SzyqOXwMl05znoPM1TF8Hky32FHf+HJocKi9P7SMlkaJNDL02Bd2PGTqD5L50u8Y=,iv:cL7FMop9aXvXHP6UJGVEDxJ8D/aBZ66aHNThKAWWGGk=,tag:2LoD5bcZLcuqaAvj02Z4/A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
