apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  chart:
    spec:
      version: ">=1.0.0-alpha"
  values:
    nextcloud:
      host: nextcloud-staging.passer.local
      configs:
        domain.config.php: |-
          <?php
          $CONFIG = array(
            'trusted_domains' => ['nextcloud-staging.passer.local', 'localhost'],
            'overwrite.cli.url' => 'https://nextcloud-staging.passer.local',
          );
    persistence:
      size: 4Gi
    livenessProbe:
      httpHeaders:
        - name: Host
          value: nextcloud-staging.passer.local
    readinessProbe:
      httpHeaders:
        - name: Host
          value: nextcloud-staging.passer.local
    startupProbe:
      httpHeaders:
        - name: Host
          value: nextcloud-staging.passer.local
    mariadb:
      primary:
        persistence:
          size: 1Gi
