apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  chart:
    spec:
      version: ">=1.0.0-alpha"
  values:
    nextcloud:
      host: nextcloud.staging
    persistence:
      size: 4Gi
    mariadb:
      primary:
        persistence:
          size: 1Gi
