apiVersion: v1
kind: Secret
metadata:
    name: findash-db
    namespace: finance
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:1y2tEht5Eg==,iv:A24peljH7VvGOAeUkDh1Nks5u/ji/d4afpbxMgvUDDE=,tag:fvY3GriY9fO/RENk2HEj9A==,type:str]
    password: ENC[AES256_GCM,data:3GEhTXIzn+yS5oVUuGK0Pb0jxfmit6/63W/SbET0HAIkA5KdrwT0A87MsU/WcVJi,iv:cQrq1wsvEM/mAeWza8IslkbCfpSvDz/2tCz2rECPQYw=,tag:lEglx5UcnCZ5DMtgR8zH9g==,type:str]
    #ENC[AES256_GCM,data:yqkWOJjUK+/+pZ4xUz53bvMNGABaQGW6e4iXq6+Ifnh+eAcqvpJZW9IMuDetEoYOYvxcvur3FdvrbzBEYAW5EJVU2cN2iqV4Bg==,iv:iydKLI0+5ZuqLjVgF5oqzg8hPeu1GMNLxllgIyT0ScQ=,tag:Chs89IZ46hD10Vx7Soz3HA==,type:comment]
    #ENC[AES256_GCM,data:QMtAjUz6MBA7Xp7b5sPj4pgCKPYTtO4xDgC6cgFZl7BQFKiaVSQoSwzsDC3I,iv:8tJ+HGcUsUG5find5pX63REpJo/ckGv/b9XzDOmdYA0=,tag:pakOeKEJz3TFLSy8s7dwcQ==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:98D288UbYJKqMzo23r7mHPeQFSDah6nWL84hR7NbVDuBGP0fCujElaoo886Y6IO5SvOHhA9ICBYtqIXWwTWGMm87n1xlaLN4Ol2FL5EFWG456IAWT+Kpd79xGxG6n0jbSjLObKb5pJkN6fbEyd9S+aibfuoIb4A2fbc83QfA5O/f4NmcRTnUhg==,iv:p1sUGeknQsJiPdFsmEYNFqnhpOhiLjqLCV7UKGGim+w=,tag:2HC1iLLZX8l6ASbQkr5zcw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUDN5MGhBMHh5UlBJT0pp
            aExwSHFXRWJqdHNWMTJMVmpIckFWYWJmSGdVClEyVElESjBGRXV1WS9CMDVoWnZi
            Nm03UVlyM0czZmNHa1Q4MDJ1K0NTSFUKLS0tIEZtNVZRdWU3WXg2WlRLWnZCMm5w
            bkUyRjNIRkh6b2R4SG1FdnJMaHg4VDAKbeZgXFrZFdZX7Rfk+UjzkXZ+HbMdx9Pb
            SkVvMjZi+q4redaSwIUtmLWeYsF4WYYhp/eOizRObSS2hlAVllTDIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15ry0az96h329q6hwvzewyl0re9gl554n73megqyk276kkrr7pvuqpyp4y8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T15:59:36Z"
    mac: ENC[AES256_GCM,data:h684hq5kJvK0wWX0caoy7mf6OrPeV3qE3taUeSOUw9uwvoz9fTs4CKYDTf2COmQH9EuEzb+nCYUoCRP+OgDgZMLBbcWU5GK7+5teDd8vfWWs06R6LdDfaH2OipGVLm5cBEC1LGgfDXIN4QZFSod1X1Iceh+Ovvsv1LVk8LELyZ4=,iv:sargqPbykKAfaF9U5yUGuWIGdqTDmpBJRVXinHruphI=,tag:+nz2gDsbbF/trtyN3ugFOg==,type:str]
    version: 3.13.3
