apiVersion: v1
kind: Secret
metadata:
    name: immich-db
    namespace: immich
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:pAueDvE=,iv:MWRp1Iy38DLJz6fK/+SRCPUHDbIuOddoEVQQQXgU5xU=,tag:21qg30hygNgOC8NoUCRwxw==,type:str]
    postgres-password: ENC[AES256_GCM,data:4wM9wDITuMz9Qw==,iv:ge5OkRAi6hrZ8spdcupacc6CFzfqtUexWo7QIUsDCZc=,tag:WverfAEWF9pTT9IzlZmKRQ==,type:str]
sops:
    age:
        - recipient: age15ry0az96h329q6hwvzewyl0re9gl554n73megqyk276kkrr7pvuqpyp4y8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZUhNek5EbTR6NG9OME9Y
            Q2VlQVVENVh0bmN1NGFyekt5OGZYdVNoQlhJCkkvWDFpeG85Mnh2RWFCcUtxUjd1
            WkJTQlJ6czg0Q3VRZko1VTd6VWVPQVkKLS0tIHdYVzVRNmZVUDNnK3ZBNFlNb1dx
            MHB5TlZIZVpoODNKRjJjSWd4QzF6YlEK6QnFPFtZj2P0lQmSbBdkXBn4Xkyeor4l
            Fi9qFToB+tZ/2fc1WrLeDWIgTtHfYt9iXBkFhykdDvGP409j+BgpVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T08:25:05Z"
    mac: ENC[AES256_GCM,data:MfbMzc4lky8g3hHZ/Lv0V8MjeoGiE1su4lOdqAzMXN4uxVf0Vwm0A+cWacR2N7HRYTed4pIJX64mvxfyKyGIDaX4DYdtr6T7EK4kJeCxpKWbJtla+D9P5i0J2JVyXmEMg+Gj9bLFDQRsl7ZF7pquLYQ9jg2uDcfYWy712oP2n3U=,iv:kiiZLe4t1eCgC88efpKVP8vXKrVTjUWhpXDvzyO7i4I=,tag:nOr73HSUyX6yl6dPhETM5Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
