apiVersion: v1
kind: Secret
metadata:
    name: immich-db
    namespace: immich
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:pAueDvE=,iv:MWRp1Iy38DLJz6fK/+SRCPUHDbIuOddoEVQQQXgU5xU=,tag:21qg30hygNgOC8NoUCRwxw==,type:str]
    postgres-password: ENC[AES256_GCM,data:4wM9wDITuMz9Qw==,iv:ge5OkRAi6hrZ8spdcupacc6CFzfqtUexWo7QIUsDCZc=,tag:WverfAEWF9pTT9IzlZmKRQ==,type:str]
    username: ENC[AES256_GCM,data:cVEgH9ej,iv:Xvyng5Uc9hdb/hXcqwB65ZV9OO4v+znI70WFYiNq/7Y=,tag:/vlqAKI57ZTNXFxVoOCr3Q==,type:str]
sops:
    age:
        - recipient: age15ry0az96h329q6hwvzewyl0re9gl554n73megqyk276kkrr7pvuqpyp4y8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZUhNek5EbTR6NG9OME9Y
            Q2VlQVVENVh0bmN1NGFyekt5OGZYdVNoQlhJCkkvWDFpeG85Mnh2RWFCcUtxUjd1
            WkJTQlJ6czg0Q3VRZko1VTd6VWVPQVkKLS0tIHdYVzVRNmZVUDNnK3ZBNFlNb1dx
            MHB5TlZIZVpoODNKRjJjSWd4QzF6YlEK6QnFPFtZj2P0lQmSbBdkXBn4Xkyeor4l
            Fi9qFToB+tZ/2fc1WrLeDWIgTtHfYt9iXBkFhykdDvGP409j+BgpVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T16:19:13Z"
    mac: ENC[AES256_GCM,data:dQukyIbLfJslIk7PGtQoJ9P6SsqyMFiDpm2kJVKvk8ExY7MiKV02oFy0TkX5rWUX7xd2TLthF+Fiy9VnL+ePPDDQx/6aKPyoJF5Ko0q8KyHQv/gQcNJhMvXzGAqgUVTgJTaqV9cnFCIYBwcxWhSn+sdhzTaerxHGie7Sn7/VNqc=,iv:DIMM4ecx+UZ+KkfBCmLo00eUNTVhW5pgI6s/EuH4Gx0=,tag:Bi99jrddt/WBGc+6LpPnJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
