apiVersion: ENC[AES256_GCM,data:F48=,iv:XJ8/ljK8Tv4VxEU74K2Glld+FkeIcXlS6DXyyM1oCkI=,tag:84x+s5RHN0osyPpefE7o2w==,type:str]
kind: ENC[AES256_GCM,data:2LaC0fU7,iv:SoFpzG7Nq9+9cCsZSP6Kw23RSX4R0GRIqmKOE29smh8=,tag:JjQzLlp8TxPXWsJnCUpsew==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UwY2VDIT1ZZX,iv:zkyhnEAukpltP0zEtPnQztHPie0Zldi/NAXLl9Bpxe8=,tag:HaovdREcU69z+d74seu/+g==,type:str]
    namespace: ENC[AES256_GCM,data:cH74EpuB,iv:KlfArbGT80fA1tevcEAEEfBg3XVFHzw/2SO2ClavXv8=,tag:6ZjktPd/jLH8Nuq6VN9OBA==,type:str]
type: ENC[AES256_GCM,data:uOInG2UR,iv:3VMlprAqJx5qaQZ73RyIbfJSERyXCXgUyTnvvmQKw48=,tag:eqictomVLH3qFD23okOMRw==,type:str]
stringData:
    password: ENC[AES256_GCM,data:cTSfp90=,iv:D8ORxN7skzYkLKdH/65IlP6+h1P6b/7vmJe4J4Sceug=,tag:tuDhLtwPh10HevNQkacdjQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:0bjYtfpAOOXoug==,iv:NBpIkQToQRvjdOxW/Sr5FZJP0M9X654XbwIMR6j1CIg=,tag:8bZWDsagsJg31xWnBbivNA==,type:str]
sops:
    age:
        - recipient: age15ry0az96h329q6hwvzewyl0re9gl554n73megqyk276kkrr7pvuqpyp4y8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cTBzOXZNT3kxRndzVGtK
            UDRac0pXT2p0RE9XdEk3NG1tNHdUdmhTVEU4CkR4UlRaeUxja3BjQXdGUDdiUFBI
            TUExZ3dIbjNKVjc0VCtkT0FybTZZZHMKLS0tIDNOdjVEYU94YjhldEdGSVFwRDlj
            WW1uY2ZLSFYwa1JEOE45ZHVVR3V3U3cKwcCFpf19otsw8WAtxOFbKPnWoO1y69g8
            mOSed63L60JHthWx7B+XF/3bGDx3W5UYRp+ApjNIKJrsKtvn9fXUPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T08:19:26Z"
    mac: ENC[AES256_GCM,data:PvTncpFllY/QFGIiBdbkiFcB3y2Mb+HEx03/VfOZjNv0W2shV/uUBIr1AvO13XauNNRWdLzjKgdMUoSkeNgZOW/4B4Xr0YR/s+UbFnOBhzP2qBY8u2bOWw1NqIgkMWbvGlU//huwi1wuL3bzUKG2Dl6KgPphv4W1kiX/LLJAsmQ=,iv:bZofnQQiUPYU1EVaiXSzJx6KdQfAqQ7bXX0AoA2YChE=,tag:6t/qtWEp4POjBrDYQMAvGQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
