apiVersion: v1
kind: Secret
metadata:
    name: immich-oidc
    namespace: immich
type: Opaque
stringData:
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:AACot+nCvmeps7souR3VRfbOQ3qiUwh4oh/0dWlVjHkLE4Mwvh6OyIG25lrN,iv:jACVErKvNllI2+rx91DX4h0x2/Al3SwS2YaI69uQy38=,tag:dElKUTRXLQM/10RkJC4LYQ==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:z/CZGwz0,iv:yH9SXFvZ256g+T/wcC4M0jtak0haaKYsl7uJbIKTENw=,tag:De66oc+aXperdWF2gd0dTg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:jfSHKKh+/G7hJIGUFV7qVPZ7IN0mr4uNdUlWchPlwZ3XQzQw+4oKpIKn4FZHXuvMFpC4VJuPKkgjkvriQhZg8w==,iv:Fppj8x4Hkn4BjVIjQpGOTXfnKIJq13btALBh5Sz1zfs=,tag:SK3Ia4BCJxIZ+DFFTDX4sQ==,type:str]
    OIDC_SCOPE: ENC[AES256_GCM,data:KPAjnGb4zFvxjBIwQthF2TcPtC8=,iv:xC3SMV4m2FeQFeoCJ8cTySqpWxuwq/okqmhMlzff8Oc=,tag:x/AP/KnXVdGUy4JnNDvODg==,type:str]
    OIDC_BUTTON_TEXT: ENC[AES256_GCM,data:1uM9j0yQnYkT7yER+/xvlWqMUkY=,iv:lRgIYe+UNSNJs4S8u6SJkqWx9StnbU8MbJyIJmiHSIg=,tag:jjaj5oRzZ+SILAxIdss48w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0OTZSdkNaU3hVRzR1YVdl
            UlVCSldGYmsvSEJadXhsRk5maTZCcEprRFFVCmw2SVdUbUdqZUtBMjJyRGJvcGFH
            dG9KMnhTWmZoVFc2Yy8wNTg3UWNwVDAKLS0tIDlEMStsUG5VbWM3K3grbkl3T0Vh
            ditxRFBJQkpoa3I0dVZBVUd6a0FUMFUKjuFTfRcZkb3fGnd8xuQfhaQBAWkDSu6/
            dO2QLL7hsHbd70tO261ip9bhRI4azqOJH7j6PAK6A2a7mGECD9FgRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15ry0az96h329q6hwvzewyl0re9gl554n73megqyk276kkrr7pvuqpyp4y8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T14:21:24Z"
    mac: ENC[AES256_GCM,data:TNyz3+uusrwi5FdwzXtZMCEn+ZJsWlgCsL1PFaRAW80f2TQLlF4e4t7hNjTmLlJOvl2+iZ5LSZcykod1bUOofXIwyEUBIZHaXvsUPFRW0EnSdWcNMBMETLl7P2QG3ZSzalqg6uhz0aeeIlRJ34uSUTqGJQT/SzmQ1OMPr+vFMlk=,iv:PhM1af/4RcNzs5kXjahnF8m+qpVTp59je59zOaITn7s=,tag:HEdRukqSs+0B38kLEqbztA==,type:str]
    version: 3.13.3
