apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - oci-repository.yaml
  - pvc.yaml
  - immich-db.secret.yaml
  - postgres.yaml
  - release.yaml
  - httproute.yaml
