apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: immich
  namespace: immich
spec:
  interval: 12h
  url: oci://ghcr.io/immich-app/immich-charts/immich
  ref:
    tag: 0.11.1
